### PR TITLE
`issymmetric`/`ishermitian` for `Circulant`

### PR DESCRIPTION
**Pull request by jishnub**
These may be computed in `O(n)` instead of the fallback `O(n^2)`

### CODE REVIEW

**Comment by putianyi889** [comment]
Why is the first entry special? `LinearAlgebra` doesn't tackle the first entry separately.

**Comment by jishnub** [comment]
The first entry corresponds to the principal diagonal. `LinearAlgebra` checks all elements, so it doesn't need to have special checks for the diagonal. One approach here could be `C.vr == vec(adjoint(C.vc))`, but since `C.vr` allocates currently, it's perhaps better to not use this. Separating out the principal diagonal makes the check easier, in my mind. How would you suggest doing it?

**Comment by putianyi889** [comment]
I'm thinking of rewritting `_circulate` and `_firstnonzero` so that they don't allocate. Then `issymmetric` and `ishermitian` can cover `AbstractToeplitz`.

**Comment by jishnub** [comment]
One way to rewrite `_circulate` could be to take on https://github.com/Vexatos/CircularArrays.jl as a dependency, so that
```julia
julia> ToeplitzMatrices._circulate(1:4)
4-element Vector{Int64}:
 1
 4
 3
 2

julia> view(CircularVector(1:4), 1:-1:-2)
4-element view(CircularVector(::UnitRange{Int64}), 1:-1:-2) with eltype Int64:
 1
 4
 3
 2
```

**Comment by putianyi889** [comment]
using `view(A, 1, :)` or `view(A, :, 1)` could also work. `OneElement` has a risk which is when you convert `TriangularToeplitz` to `Toeplitz`, an argument would stay lazy.

**Comment by jishnub** [comment]
`view(A, 1, :)` could be fine, we need to check which variant is the most performant.
> OneElement has a risk which is when you convert TriangularToeplitz to Toeplitz, an argument would stay lazy
Is this a problem? Does this break anything, other than `setindex!` into the properties?

**Comment by jishnub** [comment]
In any case, this doesn't fundamentally change the `O(n)` behavior, so I would say that we may go ahead with this PR, and change the implementation of `issymmetric` when the property access becomes performant.

**Comment by putianyi889** [comment]
The way `view(A, 1, :)` works is basically the same as `CircularArrays` or `OneElement` as they all have proprietary `getindex`. A benefit of `view` is that when you do `copy`, you get the "desired" type.

**Pull request merged**
